# =============== Meta config for experiment ===============
experiment_name = "sac_lnorm"
device = "cpu"
seed = 42
n_seeds = 100
n_steps = 1_000_000

# =============== Experiment config ===============
experiment_type = [ "SAC" ]
sample_size = 256
learning_starts = 5000
init_temperature = 1
gamma = 0.99
policy_freq = 2
target_network_freq = 1
tau = 0.005
action_repetition = 1
n_updates = 1

# Postprocessing-related
n_bins = 100

# =============== Task config ===============
[ task ]
name = [
    ["dmc", "acrobot-swingup"],
    ["dmc", "acrobot-swingup_sparse"],
    ["dmc", "ball_in_cup-catch"],
    ["dmc", "cartpole-balance"],
    ["dmc", "cartpole-balance_sparse"],
    ["dmc", "cartpole-swingup"],
    ["dmc", "cartpole-swingup_sparse"],
    ["dmc", "cartpole-two_poles"],
    ["dmc", "cartpole-three_poles"],
    ["dmc", "cheetah-run"],
    ["dmc", "finger-spin"],
    ["dmc", "finger-turn_easy"],
    ["dmc", "finger-turn_hard"],
    ["dmc", "fish-upright"],
    ["dmc", "fish-swim"],
    ["dmc", "hopper-stand"],
    ["dmc", "hopper-hop"],
    ["dmc", "manipulator-bring_ball"],
    ["dmc", "manipulator-bring_peg"],
    ["dmc", "manipulator-insert_ball"],
    ["dmc", "manipulator-insert_peg"],
    ["dmc", "pendulum-swingup"],
    ["dmc", "point_mass-easy"],
    ["dmc", "point_mass-hard"],
    ["dmc", "reacher-easy"],
    ["dmc", "reacher-hard"],
    ["dmc", "stacker-stack_2"],
    ["dmc", "stacker-stack_4"],
    ["dmc", "swimmer-swimmer6"],
    ["dmc", "swimmer-swimmer15"],
    ["dmc", "walker-stand"],
    ["dmc", "walker-walk"],
    ["dmc", "walker-run"],
    ["gym", "Ant-v4"],
    ["gym", "Hopper-v4"],
    ["gym", "Walker2d-v4"],
    ["gym", "Swimmer-v4"],
    ["gym", "Reacher-v4"],
    ["gym", "Pusher-v4"],
    ["gym", "InvertedPendulum-v4"],
    ["gym", "InvertedDoublePendulum-v4"],
    ["gym", "HalfCheetah-v4"],
]

# =============== Learner config ===============
[ learner ]
    pnorm = false

        [ learner.actor ]
            log_std_min = -5
            log_std_max = 2

            [ learner.actor.encoder ]
                arch_name = "LayernormReLUNetworkWithHook"

                [ learner.actor.encoder.kwargs ]
                    layer_sizes = [ [-1, 256, 256 ] ]
                    bias = true
                    activate_last = true

        [ learner.critic ]
            [ learner.critic.encoder ]
                arch_name = "LayernormReLUNetworkWithHook"

                [ learner.critic.encoder.kwargs ]
                    layer_sizes = [ [-1, 256, 256 ] ]
                    bias = true
                    activate_last = true

            [ learner.critic.predictor ]
                arch_name = "FCReLUNetworkWithHook"

                [ learner.critic.predictor.kwargs ]
                    layer_sizes = [ [ 256, 1 ] ]


# =============== Optimizer config ===============
[ optim ]
step_size = 3e-4

[ optim.actor ]
name = "Adam"
[ optim.actor.kwargs]

[ optim.critic ]
name = "Adam"
[ optim.critic.kwargs ]
lr = 1e-3

# =============== Optimizer config ===============
[ replay_buffer ]
size = 1_000_005
